---
layout: post
title: 第十二章 异常、智能指针
category: CPP基础
tags: CPP基础
description: CPP基础
---  

## 异常
1. 错误
    1. 编程过程中的常见错误类型
    2. 语法错误
    3. 逻辑错误
    4. 异常
    5. ...
2. 异常
    1. 异常是一种在程序运行过程中的发生的不好预测的错误(比如内存不够)
    2. 异常没有被处理，会导致程序终止
    3. 系统异常：
        1. 某些时候写代码导致系统会主动抛出异常
            
            ```
            //系统抛出异常
            cout << "1" << endl;
            //如果内存不够，就会抛出异常（运行过程中抛出一个错误）
            try { //可能会出现错误的代码放在这里
            	for (int i = 0; i < 9999999; i++) {
            		int *p = new int[9999999];
                
            	}
            	//这句代码不会指向
            	//try中的代码，只要某一句出现异常，后面的代码就不会执行
            	cout << "2" << endl;
            }
              //}catch (const std::exception&){ //catch（）参数是异常类型。
            catch (...) {  //... 表示拦截所有的异常类型
            	cout << "发生了异常" << endl;
            }
            cout << "3" << endl;
            ```
    4. 主动抛出异常
        1. 有些时候，系统不会主动抛出异常，这就需要我们主动抛出异常-throw
        2. throw异常后，会在**当前函数**中查找匹配的catch，找不到就 终止当前函数代码，去**上一层函数**中查找。如果最终都找不 到匹配的catch，整个程序就会终止（**注意理解！！！**）
            
            ```
            
            int divide(int a, int b) {
                //因为b=0时，系统不会抛出异常，因此，只能我们主动抛出异常
                //if (!b) throw 6;
                if (!b) throw "字符串异常";
                return a / b;
            }
            int main() {
            cout << "1" << endl;
            try{
            	int  v1 = 10;
            	int v2 = 0;
            	cout << divide(v1, v2) << endl;
            }catch (int exception){//捕捉整形异常
            	cout << "发生了异常-"<<exception << endl;
            }catch (const char *exception) {//捕捉字符串异常
            	cout << "发生了异常-"<<exception << endl;
            }
            
            cout << "2" << endl;
            getchar();
            return 0;
            }
            ```
    5. 异常的抛出声明
        1. 为了增强可读性和方便团队协作，如果函数内部可能会抛出异常，建议函数声明一下异常类型
            
            ```
            //抛出任何可能的异常
            void func1() {
            
            }
            //不抛出任何异常
            void func2() throw() {
            
            }
            //只抛出int、double类型的异常
            void func3() throw(int,double) {
             }
             
             //别人调用
             try{
            	func3();
            
            }catch ( int exp)
            {
            
            }catch (double exp){
            }
            ```
    6. 自定义异常类型
        1. 有时候觉得系统自带的异常没有明确的意思，这就需要我们自己定义异常
            
            ```
            //自定义异常
            //基础类
            class Exception {
            public :
            	//纯虚函数
            	virtual string what() const = 0;
            };
            //除法错误异常
            class DivideException :public Exception {
            public:
            	string what()const {
            		return "不能除以0！";
            	}
            };
            //加法错误异常
            class AddException :public Exception {
            
            };
            
            int divide(int v1, int v2) throw(Exception) {
            	if (v2 == 0) throw DivideException();
            	return v1 / v2;
            }
            int main() {
            
            	try{
            		int a = 10;
            		int b = 0;
            		int c = divide(a, b);
            
            	//const 是即可以接受常量，也可以接受非常量
            	}catch (const Exception &exception){
            		//常量调用方法，必须是常量方法，所以what（）是常量方法
            		cout << exception.what() << endl;
            	}
            }
            ```
    7. 标准异常(std)
        
        ![图1](https://raw.githubusercontent.com/zhoghua123/imgsBed/master/cpp19.png)
        
        1. 这些事系统定义的异常
        2. 代码举例：
        
        ```
        try {
            for (int i = 0; i < 9999999; i++) {
                int *p = new int[9999999];
            }
        }catch (std:: bad_alloc exception) {  //bad_alloc:内存分配异常
            cout << exception.what() << endl;
        }
        ```

